### ISSUE TITLE
Ansible deprecation warnings on build

### ISSUE THREAD

**Issue by bryjbrown** [Islandora-Devops/claw-playbook#19]
This message displays after all the ansible roles download/extract/install:

```
[DEPRECATION WARNING]: 'include' for playbook includes. You should use 
'import_playbook' instead. This feature will be removed in version 2.8. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in 
ansible.cfg.
[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use 
'import_tasks' for static inclusions or 'include_tasks' for dynamic inclusions.
 This feature will be removed in a future release. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is
 discouraged. The module documentation details page may explain more about this
 rationale.. This feature will be removed in a future release. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: The use of 'static' has been deprecated. Use 
'import_tasks' for static inclusion, or 'include_tasks' for dynamic inclusion. 
This feature will be removed in a future release. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.
```

Since we're aiming to make CLAW as future-proof as possible, we'll want to get rid of these. Not urgent, but something to consider.

**Comment by jonathangreen** [comment]
Kind of the same advice as I offered in the other thread, I bet this is a Ansible 2.4 issue. 

Do you get any info from Ansible line numbers or anything where these warnings occur. I can't think of anywhere we are doing an include to include a playbook, so I'm thinking its probably happening in the roles we are dependant on. If you do have some line number info, maybe bump the version number of those roles, or if not maybe try bumping them all.

**Comment by bryjbrown** [comment]
@jonathangreen No line numbers, like it I said it spits this block out right after the initial download/extract/install roles phase. 

My understanding is that Ansible considers the smaller app specific .yml files used by playbook.yml to be themselves playbooks, so its complaining about stuff like this: https://github.com/Islandora-Devops/claw-playbook/blob/master/playbook.yml#L3-L9. I think the `include` keyword is getting deprecated across the board in favor of the more specific `import_playbook`. See https://docs.ansible.com/ansible/devel/playbooks_reuse_includes.html#importing-playbooks for more specific examples of this.
