### ISSUE TITLE
Pulling changes for 2.0.0 causes directory not found error on fresh build

### ISSUE THREAD

**Issue by alxp** [Islandora-Devops/claw-playbook#244]
Just pulled the changes made for the 2.0.0 release on to my local instance.

I did not set any new variables so I can test default behaviour.

Then running vagrant up produces the following error:

```bash

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'islandora_base' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'islandora_base' (v0) for provider: virtualbox
    default: Downloading: islandora_base
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /Users/aoneill/dev/islandora-playbook/islandora_base

```
Is this folder meant to exist? Perhaps because you can't normally check empty folders in to Git it is not there for me.

cc @whikloj  @rosiel

**Comment by rosiel** [comment]
The first time you run `vagrant up`, you need to set `ISLANDORA_INSTALL_BASE=true`

I've updated the README and there is an **[open PR](https://github.com/Islandora/documentation/pull/2191)** for the official documentation. 

Once you export it to a base box (at this point the steps are only in the Documentation PR, though maybe it belongs in the README too?) then `islandora_base` will be a ~2GB base box file in your playbook directory.
