### ISSUE TITLE
Playbook failing again

### ISSUE THREAD

**Issue by BrzIGH** [Islandora-Devops/claw-playbook#276]
Last week I tried running a playbook that has served me well since the beginning of the year. It failed.
Re-downloaded the external roles and tried again. Failed again.
Built a brand new Ubuntu 22.04.4 LTS box and redownloaded the complete playbook and external roles. It failed again.

Here is where I consistently get the error:

TASK [geerlingguy.drupal : Generate Drupal project with composer package in /tmp/composer-project (this may take a while).] *************************************************************
Tuesday 09 April 2024  14:21:59 -0700 (0:00:00.532)       0:00:11.516 ********* 
fatal: [default]: FAILED! => {"changed": true, "cmd": ["/usr/local/bin/composer", "create-project", "islandora/islandora-starter-site:^1.2", "/tmp/composer-project", "--prefer-dist", "--no-interaction"], "delta": "0:00:03.856174", "end": "2024-04-09 14:22:03.979512", "msg": "non-zero return code", "rc": 2, "start": "2024-04-09 14:22:00.123338", "stderr": "Creating a \"islandora/islandora-starter-site:^1.2\" project at \"/tmp/composer-project\"\nInstalling islandora/islandora-starter-site (1.6.2)\n  - Downloading islandora/islandora-starter-site (1.6.2)\n  - Installing islandora/islandora-starter-site (1.6.2): Extracting archive\nCreated project in /tmp/composer-project\n> Islandora\\StarterSite::rootPackageInstall\nInstalling dependencies from lock file (including require-dev)\nVerifying lock file contents can be installed on current platform.\nYour lock file does not contain a compatible set of packages. Please run composer update.\n\n  Problem 1\n    - seboettg/citeproc-php is locked to version v2.6.2 and an update of this package was not requested.\n    - seboettg/citeproc-php v2.6.2 requires ext-intl * -> it is missing from your system. Install or enable PHP's intl extension.\n  Problem 2\n    - seboettg/citeproc-php v2.6.2 requires ext-intl * -> it is missing from your system. Install or enable PHP's intl extension.\n    - drupal/citation_select 2.0.0-beta1 requires seboettg/citeproc-php ^2.6 -> satisfiable by seboettg/citeproc-php[v2.6.2].\n    - drupal/citation_select is locked to version 2.0.0-beta1 and an update of this package was not requested.\n\nTo enable extensions, verify that they are enabled in your .ini files:\n    - /etc/php/8.1/cli/php.ini\n    - /etc/php/8.1/cli/conf.d/10-mysqlnd.ini\n    - /etc/php/8.1/cli/conf.d/10-opcache.ini\n    - /etc/php/8.1/cli/conf.d/10-pdo.ini\n    - /etc/php/8.1/cli/conf.d/15-xml.ini\n    - /etc/php/8.1/cli/conf.d/20-apcu.ini\n    - /etc/php/8.1/cli/conf.d/20-calendar.ini\n    - /etc/php/8.1/cli/conf.d/20-ctype.ini\n    - /etc/php/8.1/cli/conf.d/20-curl.ini\n    - /etc/php/8.1/cli/conf.d/20-dom.ini\n    - /etc/php/8.1/cli/conf.d/20-exif.ini\n    - /etc/php/8.1/cli/conf.d/20-ffi.ini\n    - /etc/php/8.1/cli/conf.d/20-fileinfo.ini\n    - /etc/php/8.1/cli/conf.d/20-ftp.ini\n    - /etc/php/8.1/cli/conf.d/20-gd.ini\n    - /etc/php/8.1/cli/conf.d/20-gettext.ini\n    - /etc/php/8.1/cli/conf.d/20-iconv.ini\n    - /etc/php/8.1/cli/conf.d/20-imap.ini\n    - /etc/php/8.1/cli/conf.d/20-mbstring.ini\n    - /etc/php/8.1/cli/conf.d/20-mysqli.ini\n    - /etc/php/8.1/cli/conf.d/20-pdo_mysql.ini\n    - /etc/php/8.1/cli/conf.d/20-pdo_pgsql.ini\n    - /etc/php/8.1/cli/conf.d/20-pdo_sqlite.ini\n    - /etc/php/8.1/cli/conf.d/20-pgsql.ini\n    - /etc/php/8.1/cli/conf.d/20-phar.ini\n    - /etc/php/8.1/cli/conf.d/20-posix.ini\n    - /etc/php/8.1/cli/conf.d/20-readline.ini\n    - /etc/php/8.1/cli/conf.d/20-shmop.ini\n    - /etc/php/8.1/cli/conf.d/20-simplexml.ini\n    - /etc/php/8.1/cli/conf.d/20-sockets.ini\n    - /etc/php/8.1/cli/conf.d/20-sqlite3.ini\n    - /etc/php/8.1/cli/conf.d/20-sysvmsg.ini\n    - /etc/php/8.1/cli/conf.d/20-sysvsem.ini\n    - /etc/php/8.1/cli/conf.d/20-sysvshm.ini\n    - /etc/php/8.1/cli/conf.d/20-tokenizer.ini\n    - /etc/php/8.1/cli/conf.d/20-xmlreader.ini\n    - /etc/php/8.1/cli/conf.d/20-xmlwriter.ini\n    - /etc/php/8.1/cli/conf.d/20-xsl.ini\n    - /etc/php/8.1/cli/conf.d/20-yaml.ini\nYou can also run `php --ini` in a terminal to see which files are used by PHP in CLI mode.\nAlternatively, you can run Composer with `--ignore-platform-req=ext-intl` to temporarily ignore these required extensions.", "stderr_lines": ["Creating a \"islandora/islandora-starter-site:^1.2\" project at \"/tmp/composer-project\"", "Installing islandora/islandora-starter-site (1.6.2)", "  - Downloading islandora/islandora-starter-site (1.6.2)", "  - Installing islandora/islandora-starter-site (1.6.2): Extracting archive", "Created project in /tmp/composer-project", "> Islandora\\StarterSite::rootPackageInstall", "Installing dependencies from lock file (including require-dev)", "Verifying lock file contents can be installed on current platform.", "Your lock file does not contain a compatible set of packages. Please run composer update.", "", "  Problem 1", "    - seboettg/citeproc-php is locked to version v2.6.2 and an update of this package was not requested.", "    - seboettg/citeproc-php v2.6.2 requires ext-intl * -> it is missing from your system. Install or enable PHP's intl extension.", "  Problem 2", "    - seboettg/citeproc-php v2.6.2 requires ext-intl * -> it is missing from your system. Install or enable PHP's intl extension.", "    - drupal/citation_select 2.0.0-beta1 requires seboettg/citeproc-php ^2.6 -> satisfiable by seboettg/citeproc-php[v2.6.2].", "    - drupal/citation_select is locked to version 2.0.0-beta1 and an update of this package was not requested.", "", "To enable extensions, verify that they are enabled in your .ini files:", "    - /etc/php/8.1/cli/php.ini", "    - /etc/php/8.1/cli/conf.d/10-mysqlnd.ini", "    - /etc/php/8.1/cli/conf.d/10-opcache.ini", "    - /etc/php/8.1/cli/conf.d/10-pdo.ini", "    - /etc/php/8.1/cli/conf.d/15-xml.ini", "    - /etc/php/8.1/cli/conf.d/20-apcu.ini", "    - /etc/php/8.1/cli/conf.d/20-calendar.ini", "    - /etc/php/8.1/cli/conf.d/20-ctype.ini", "    - /etc/php/8.1/cli/conf.d/20-curl.ini", "    - /etc/php/8.1/cli/conf.d/20-dom.ini", "    - /etc/php/8.1/cli/conf.d/20-exif.ini", "    - /etc/php/8.1/cli/conf.d/20-ffi.ini", "    - /etc/php/8.1/cli/conf.d/20-fileinfo.ini", "    - /etc/php/8.1/cli/conf.d/20-ftp.ini", "    - /etc/php/8.1/cli/conf.d/20-gd.ini", "    - /etc/php/8.1/cli/conf.d/20-gettext.ini", "    - /etc/php/8.1/cli/conf.d/20-iconv.ini", "    - /etc/php/8.1/cli/conf.d/20-imap.ini", "    - /etc/php/8.1/cli/conf.d/20-mbstring.ini", "    - /etc/php/8.1/cli/conf.d/20-mysqli.ini", "    - /etc/php/8.1/cli/conf.d/20-pdo_mysql.ini", "    - /etc/php/8.1/cli/conf.d/20-pdo_pgsql.ini", "    - /etc/php/8.1/cli/conf.d/20-pdo_sqlite.ini", "    - /etc/php/8.1/cli/conf.d/20-pgsql.ini", "    - /etc/php/8.1/cli/conf.d/20-phar.ini", "    - /etc/php/8.1/cli/conf.d/20-posix.ini", "    - /etc/php/8.1/cli/conf.d/20-readline.ini", "    - /etc/php/8.1/cli/conf.d/20-shmop.ini", "    - /etc/php/8.1/cli/conf.d/20-simplexml.ini", "    - /etc/php/8.1/cli/conf.d/20-sockets.ini", "    - /etc/php/8.1/cli/conf.d/20-sqlite3.ini", "    - /etc/php/8.1/cli/conf.d/20-sysvmsg.ini", "    - /etc/php/8.1/cli/conf.d/20-sysvsem.ini", "    - /etc/php/8.1/cli/conf.d/20-sysvshm.ini", "    - /etc/php/8.1/cli/conf.d/20-tokenizer.ini", "    - /etc/php/8.1/cli/conf.d/20-xmlreader.ini", "    - /etc/php/8.1/cli/conf.d/20-xmlwriter.ini", "    - /etc/php/8.1/cli/conf.d/20-xsl.ini", "    - /etc/php/8.1/cli/conf.d/20-yaml.ini", "You can also run `php --ini` in a terminal to see which files are used by PHP in CLI mode.", "Alternatively, you can run Composer with `--ignore-platform-req=ext-intl` to temporarily ignore these required extensions."], "stdout": "", "stdout_lines": []}

Thanks

**Comment by BrzIGH** [comment]
After manually installing the php intl extension the installation went fine.
Looks like one of the tasks needs a small update to reflect this.

**Comment by bdgregg** [comment]
I had to add '  - "php{{ php_version }}-intl"' to my islandora-playbook/vars/Debian.yml file to install php intl module to get this to work properly.  My Debian.yml file looks like the following: 
`php_packages_extra:
  - "libapache2-mod-php{{ php_version }}"
  - "php{{ php_version }}-mysql"
  - "php{{ php_version }}-pgsql"
  - "php{{ php_version }}-gd"
  - "php{{ php_version }}-xml"
  - "php{{ php_version }}-curl"
  - "php{{ php_version }}-intl"
`

**Comment by rosiel** [comment]
I'll add this in a PR.
