### ISSUE TITLE
Ansible script fails

### ISSUE THREAD

**Issue by BrzIGH** [Islandora-Devops/claw-playbook#283]
Hi,
I downaloded the latest playbook. When I target a 22.04 LTS box Iget the error below :

TASK [geerlingguy.java : Include version-specific variables for Ubuntu.] ******************
fatal: [default]: FAILED! => {"ansible_facts": {}, "ansible_included_var_files": [], "changed": false, "message": "Could not find or access 'Ubuntu-24.yml'\nSearched in:\n\t/home/innopac/islandora-playbook/roles/external/geerlingguy.java/vars/Ubuntu-24.yml\n\t/home/innopac/islandora-playbook/roles/external/geerlingguy.java/Ubuntu-24.yml\n\t/home/innopac/islandora-playbook/roles/external/geerlingguy.java/tasks/vars/Ubuntu-24.yml\n\t/home/innopac/islandora-playbook/roles/external/geerlingguy.java/tasks/Ubuntu-24.yml\n\t/home/innopac/islandora-playbook/vars/Ubuntu-24.yml\n\t/home/innopac/islandora-playbook/Ubuntu-24.yml on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}

PLAY RECAP ********************************************************************************
default                    : ok=118  changed=30   unreachable=0    failed=1    skipped=173  rescued=0    ignored=0   

Theres is no Ubuntu-24.yml file in the specified location.

What options (if any) do I have ?

Thanks

**Comment by seth-shaw-asu** [comment]
You may want to try targeting a Debian box instead. There are various parts of the scripts where we condition on Debian or Redhat, but don't have a condition for Ubuntu specifically. E.g. https://github.com/Islandora-Devops/islandora-playbook/blob/38dcff203cdbf6e267612365f38a220ec293b638/solr.yml#L8-L13

**Comment by seth-shaw-asu** [comment]
Either that or you may need to Grep for Debian in your copy and make the appropriate edits to make it work with Ubuntu.

**Comment by adam-vessey** [comment]
Just double-checking: You indicate:

> When I target a 22.04 LTS

Are you sure it was `22.04`, and not `24.04`?

As in, the attempt to access/use `Ubuntu-24.yml` is from the major version of the upstream role: https://github.com/geerlingguy/ansible-role-java/blob/5c2cf164875aaa205b3af7b915bfd061862f7d36/tasks/main.yml#L22-L24

It may be that the playbook just needs to be updated to point to a newer version of `geerlingguy.java`? Presently, [the playbook points at `2.2.0`](https://github.com/Islandora-Devops/islandora-playbook/blob/38dcff203cdbf6e267612365f38a220ec293b638/requirements.yml#L34-L35); however, [`Ubuntu-24.yml` was only introduced with `2.5.0`](https://github.com/geerlingguy/ansible-role-java/commit/bc874693ca3d04470a01e8a88862e777b36d59bb).

**Comment by BrzIGH** [comment]
Yes, I am pointing to 22.04.5 LTS. I am presuming that the current script is not 24.04-compatible yet.

**Comment by adam-vessey** [comment]
Is the host system Ubuntu 24? As in: nothing should be attempting to access `Ubuntu-24.yml` if there's no `24.*` version of Ubuntu in play; the [var lookup code using the major version is/was much the same in 2.2.0](https://github.com/geerlingguy/ansible-role-java/blob/c089506c90f838ede55a304841a003ecfdf2a07c/tasks/main.yml#L17-L19). If the host system is Ubuntu 24, is there something extra in the inventory that has it gathering the variables for the host machine, instead of/in addition to whatever target Ubuntu 22 machine? Unknown if it would attempt to get the variables for things even that it might not be running against?

... I guess what I'm getting at is: More environmental information could be useful in attempting to figure things out.

**Comment by BrzIGH** [comment]
Both source and target are 22.04.

**Comment by BrzIGH** [comment]
I simply copied /islandora-playbook/roles/external/geerlingguy.java/vars/Ubuntu-22.yml to /islandora-playbook/roles/external/geerlingguy.java/vars/Ubuntu-24.yml and it seems it worked. Looking at the site now to see if there are any issues.
Built on Ubuntu 22.04.5 LTS

**Comment by seth-shaw-asu** [comment]
@BrzIGH , if everything is going okay now, can we close the issue?

**Comment by BrzIGH** [comment]
I will be testing automatic derivative creation on the new build. Will report back with results.

**Comment by BrzIGH** [comment]
Derivatives have been created. Call can be closed. Thanks !
